### ISSUE TITLE
Модель CarWashModel  обновление.

### ISSUE THREAD

**Issue by PavelPrist** [web-Nearest-car-wash/car_wash_backend#31]

**Comment by PavelPrist** [comment]
Поля

contacts,
coordinates,
geo_user,
image,
legal_person(работа с юр лицами),
loyalty,
metro
name,
price_list,
promotions,
rating,
schedule,
services,
type,
over_information


какие доп модели, связи подумать самому:

contacts,  —> модель ContactsModel
coordinates,
geo_user   —>  модель  GeoUserModel,
image ,
legal_person(работа с юр лицами),
loyalty,
metro  
name,
price_list,
promotions  —> модель  PromotionsModel,
rating, 
schedule  —>  модель  ScheduleModel,
services   —>  модель  ServicesModel,
type         —>  модель  TypeCarWashModel,

**Comment by PavelPrist** [comment]
coordinates = models.CharField(
        "Координаты Ш,Д",
        blank=True,
        max_length=200,
        validators=[
            RegexValidator(
                regex=("^-?([0-8]?[0-9]|90)(\.[0-9]{1,10}),"
                       "([0-9]{1,2}|1[0-7][0-9]|180)(\.[0-9]{1,10})$"),
                message='Неверные координаты, '
                        'должны быть вида 55.752378,37.609289',
            ),
        ]
    )

с этим полем подумать, подстроить под json  яндекса

**Comment by Aleksandr140590** [comment]
Модельку контакты лучше связать через onetoone
