### ISSUE TITLE
CarWashServicesModel  добавить поле

### ISSUE THREAD

**Issue by PavelPrist** [web-Nearest-car-wash/car_wash_backend#47]

**Comment by PavelPrist** [comment]
добавить поле в модель 
способы оплаты
payment_methods  
сделать выбор поле с вариантами: карта, наличные, СБП

**Comment by Aleksandr140590** [comment]
Их же может быть несколько?

**Comment by PavelPrist** [comment]
тогда вариант с доп моделью

**Comment by PavelPrist** [comment]
или как-то так

from multiselectfield import MultiSelectField

class StoreModel(models.Model):
    PAYMENT_CHOICES = (
        ('cash', 'Наличные'),
        ('card', 'Картой'),
        ('online', 'Онлайн'),
    )
    payment = MultiSelectField(choices=PAYMENT_CHOICES, default='cash', max_choices=3, verbose_name='Способ оплаты')
